[package]
name = "skelly-demo"
version = "0.0.0"
edition = "2018"
authors = ["Zakarum"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
skelly = { path = "..", features = ["ik"] }
na = { version = "0.31", package = "nalgebra" }
macroquad = "0.3.0-alpha.15"
